version: '3.8'

services:
  bot:
    build: .
    container_name: university-parser-bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: parser-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - bot-network

  # Опционально: PostgreSQL вместо SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: parser-postgres
  #   environment:
  #     POSTGRES_DB: parser_bot
  #     POSTGRES_USER: parser
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - bot-network

volumes:
  redis_data:
  # postgres_data:

networks:
  bot-network:
    driver: bridge
